import React from 'react';
import { Inter } from 'next/font/google';
import Header from '../components/Header';
import Footer from '../components/Footer';
import 'bootstrap/dist/css/bootstrap.min.css';
import MiddleSectionIcons from '@/components/MiddleSectionIcons';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Big Step Consulting',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add any additional <head> tags here */}
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <MiddleSectionIcons/>                   
        <Footer />
      </body>
    </html>
  );
}
